# Generated by Django 3.0.6 on 2020-05-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
