# Generated by Django 3.0.6 on 2020-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200510_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/kk.jpg', upload_to='images/'),
        ),
    ]
